/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.redhat.japan.demo.machine;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Machine extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3367549156328887680L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Machine\",\"namespace\":\"com.redhat.japan.demo.machine\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"temp\",\"type\":\"int\"},{\"name\":\"rotation\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Machine> ENCODER =
      new BinaryMessageEncoder<Machine>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Machine> DECODER =
      new BinaryMessageDecoder<Machine>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Machine> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Machine> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Machine> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Machine>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Machine to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Machine from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Machine instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Machine fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private int temp;
   private int rotation;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Machine() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param temp The new value for temp
   * @param rotation The new value for rotation
   */
  public Machine(java.lang.CharSequence id, java.lang.Integer temp, java.lang.Integer rotation) {
    this.id = id;
    this.temp = temp;
    this.rotation = rotation;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return temp;
    case 2: return rotation;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: temp = (java.lang.Integer)value$; break;
    case 2: rotation = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'temp' field.
   * @return The value of the 'temp' field.
   */
  public int getTemp() {
    return temp;
  }


  /**
   * Sets the value of the 'temp' field.
   * @param value the value to set.
   */
  public void setTemp(int value) {
    this.temp = value;
  }

  /**
   * Gets the value of the 'rotation' field.
   * @return The value of the 'rotation' field.
   */
  public int getRotation() {
    return rotation;
  }


  /**
   * Sets the value of the 'rotation' field.
   * @param value the value to set.
   */
  public void setRotation(int value) {
    this.rotation = value;
  }

  /**
   * Creates a new Machine RecordBuilder.
   * @return A new Machine RecordBuilder
   */
  public static com.redhat.japan.demo.machine.Machine.Builder newBuilder() {
    return new com.redhat.japan.demo.machine.Machine.Builder();
  }

  /**
   * Creates a new Machine RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Machine RecordBuilder
   */
  public static com.redhat.japan.demo.machine.Machine.Builder newBuilder(com.redhat.japan.demo.machine.Machine.Builder other) {
    if (other == null) {
      return new com.redhat.japan.demo.machine.Machine.Builder();
    } else {
      return new com.redhat.japan.demo.machine.Machine.Builder(other);
    }
  }

  /**
   * Creates a new Machine RecordBuilder by copying an existing Machine instance.
   * @param other The existing instance to copy.
   * @return A new Machine RecordBuilder
   */
  public static com.redhat.japan.demo.machine.Machine.Builder newBuilder(com.redhat.japan.demo.machine.Machine other) {
    if (other == null) {
      return new com.redhat.japan.demo.machine.Machine.Builder();
    } else {
      return new com.redhat.japan.demo.machine.Machine.Builder(other);
    }
  }

  /**
   * RecordBuilder for Machine instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Machine>
    implements org.apache.avro.data.RecordBuilder<Machine> {

    private java.lang.CharSequence id;
    private int temp;
    private int rotation;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.redhat.japan.demo.machine.Machine.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.temp)) {
        this.temp = data().deepCopy(fields()[1].schema(), other.temp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.rotation)) {
        this.rotation = data().deepCopy(fields()[2].schema(), other.rotation);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Machine instance
     * @param other The existing instance to copy.
     */
    private Builder(com.redhat.japan.demo.machine.Machine other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.temp)) {
        this.temp = data().deepCopy(fields()[1].schema(), other.temp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.rotation)) {
        this.rotation = data().deepCopy(fields()[2].schema(), other.rotation);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.redhat.japan.demo.machine.Machine.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.redhat.japan.demo.machine.Machine.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'temp' field.
      * @return The value.
      */
    public int getTemp() {
      return temp;
    }


    /**
      * Sets the value of the 'temp' field.
      * @param value The value of 'temp'.
      * @return This builder.
      */
    public com.redhat.japan.demo.machine.Machine.Builder setTemp(int value) {
      validate(fields()[1], value);
      this.temp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'temp' field has been set.
      * @return True if the 'temp' field has been set, false otherwise.
      */
    public boolean hasTemp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'temp' field.
      * @return This builder.
      */
    public com.redhat.japan.demo.machine.Machine.Builder clearTemp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'rotation' field.
      * @return The value.
      */
    public int getRotation() {
      return rotation;
    }


    /**
      * Sets the value of the 'rotation' field.
      * @param value The value of 'rotation'.
      * @return This builder.
      */
    public com.redhat.japan.demo.machine.Machine.Builder setRotation(int value) {
      validate(fields()[2], value);
      this.rotation = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'rotation' field has been set.
      * @return True if the 'rotation' field has been set, false otherwise.
      */
    public boolean hasRotation() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'rotation' field.
      * @return This builder.
      */
    public com.redhat.japan.demo.machine.Machine.Builder clearRotation() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Machine build() {
      try {
        Machine record = new Machine();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.temp = fieldSetFlags()[1] ? this.temp : (java.lang.Integer) defaultValue(fields()[1]);
        record.rotation = fieldSetFlags()[2] ? this.rotation : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Machine>
    WRITER$ = (org.apache.avro.io.DatumWriter<Machine>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Machine>
    READER$ = (org.apache.avro.io.DatumReader<Machine>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeInt(this.temp);

    out.writeInt(this.rotation);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.temp = in.readInt();

      this.rotation = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.temp = in.readInt();
          break;

        case 2:
          this.rotation = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










